// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: pickuppoint.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PickUpPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contact string `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
}

func (x *PickUpPoint) Reset() {
	*x = PickUpPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPoint) ProtoMessage() {}

func (x *PickUpPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPoint.ProtoReflect.Descriptor instead.
func (*PickUpPoint) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{0}
}

func (x *PickUpPoint) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PickUpPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PickUpPoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PickUpPoint) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type PickUpPointCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point *PickUpPoint `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *PickUpPointCreateRequest) Reset() {
	*x = PickUpPointCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointCreateRequest) ProtoMessage() {}

func (x *PickUpPointCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointCreateRequest.ProtoReflect.Descriptor instead.
func (*PickUpPointCreateRequest) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{1}
}

func (x *PickUpPointCreateRequest) GetPoint() *PickUpPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type PickUpPointCreateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PickUpPointCreateResult) Reset() {
	*x = PickUpPointCreateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointCreateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointCreateResult) ProtoMessage() {}

func (x *PickUpPointCreateResult) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointCreateResult.ProtoReflect.Descriptor instead.
func (*PickUpPointCreateResult) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{2}
}

type PickUpPointListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PickUpPointListRequest) Reset() {
	*x = PickUpPointListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointListRequest) ProtoMessage() {}

func (x *PickUpPointListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointListRequest.ProtoReflect.Descriptor instead.
func (*PickUpPointListRequest) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{3}
}

type PickUpPointListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*PickUpPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *PickUpPointListResult) Reset() {
	*x = PickUpPointListResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointListResult) ProtoMessage() {}

func (x *PickUpPointListResult) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointListResult.ProtoReflect.Descriptor instead.
func (*PickUpPointListResult) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{4}
}

func (x *PickUpPointListResult) GetPoints() []*PickUpPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type PickUpPointGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PickUpPointGetRequest) Reset() {
	*x = PickUpPointGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointGetRequest) ProtoMessage() {}

func (x *PickUpPointGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointGetRequest.ProtoReflect.Descriptor instead.
func (*PickUpPointGetRequest) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{5}
}

func (x *PickUpPointGetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PickUpPointGetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point *PickUpPoint `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *PickUpPointGetResult) Reset() {
	*x = PickUpPointGetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointGetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointGetResult) ProtoMessage() {}

func (x *PickUpPointGetResult) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointGetResult.ProtoReflect.Descriptor instead.
func (*PickUpPointGetResult) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{6}
}

func (x *PickUpPointGetResult) GetPoint() *PickUpPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type PickUpPointUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point *PickUpPoint `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *PickUpPointUpdateRequest) Reset() {
	*x = PickUpPointUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointUpdateRequest) ProtoMessage() {}

func (x *PickUpPointUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointUpdateRequest.ProtoReflect.Descriptor instead.
func (*PickUpPointUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{7}
}

func (x *PickUpPointUpdateRequest) GetPoint() *PickUpPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type PickUpPointUpdateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PickUpPointUpdateResult) Reset() {
	*x = PickUpPointUpdateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointUpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointUpdateResult) ProtoMessage() {}

func (x *PickUpPointUpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointUpdateResult.ProtoReflect.Descriptor instead.
func (*PickUpPointUpdateResult) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{8}
}

type PickUpPointDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PickUpPointDeleteRequest) Reset() {
	*x = PickUpPointDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointDeleteRequest) ProtoMessage() {}

func (x *PickUpPointDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointDeleteRequest.ProtoReflect.Descriptor instead.
func (*PickUpPointDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{9}
}

func (x *PickUpPointDeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PickUpPointDeleteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PickUpPointDeleteResult) Reset() {
	*x = PickUpPointDeleteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pickuppoint_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickUpPointDeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpPointDeleteResult) ProtoMessage() {}

func (x *PickUpPointDeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_pickuppoint_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpPointDeleteResult.ProtoReflect.Descriptor instead.
func (*PickUpPointDeleteResult) Descriptor() ([]byte, []int) {
	return file_pickuppoint_proto_rawDescGZIP(), []int{10}
}

var File_pickuppoint_proto protoreflect.FileDescriptor

var file_pickuppoint_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x22, 0x65, 0x0a, 0x0b, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22, 0x4a, 0x0a, 0x18, 0x50, 0x69, 0x63, 0x6b, 0x55,
	0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x18,
	0x0a, 0x16, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x15, 0x50, 0x69, 0x63, 0x6b,
	0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x14,
	0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x18, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69,
	0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x22, 0x19, 0x0a, 0x17, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2a, 0x0a, 0x18, 0x50,
	0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x50, 0x69, 0x63, 0x6b, 0x55,
	0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0xc2, 0x03, 0x0a, 0x12, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x69, 0x63,
	0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x12, 0x51, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x70, 0x69, 0x63,
	0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69,
	0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x22, 0x2e, 0x70,
	0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55,
	0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50,
	0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x25, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69,
	0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x57,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x69,
	0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pickuppoint_proto_rawDescOnce sync.Once
	file_pickuppoint_proto_rawDescData = file_pickuppoint_proto_rawDesc
)

func file_pickuppoint_proto_rawDescGZIP() []byte {
	file_pickuppoint_proto_rawDescOnce.Do(func() {
		file_pickuppoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_pickuppoint_proto_rawDescData)
	})
	return file_pickuppoint_proto_rawDescData
}

var file_pickuppoint_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pickuppoint_proto_goTypes = []interface{}{
	(*PickUpPoint)(nil),              // 0: pickuppoint.PickUpPoint
	(*PickUpPointCreateRequest)(nil), // 1: pickuppoint.PickUpPointCreateRequest
	(*PickUpPointCreateResult)(nil),  // 2: pickuppoint.PickUpPointCreateResult
	(*PickUpPointListRequest)(nil),   // 3: pickuppoint.PickUpPointListRequest
	(*PickUpPointListResult)(nil),    // 4: pickuppoint.PickUpPointListResult
	(*PickUpPointGetRequest)(nil),    // 5: pickuppoint.PickUpPointGetRequest
	(*PickUpPointGetResult)(nil),     // 6: pickuppoint.PickUpPointGetResult
	(*PickUpPointUpdateRequest)(nil), // 7: pickuppoint.PickUpPointUpdateRequest
	(*PickUpPointUpdateResult)(nil),  // 8: pickuppoint.PickUpPointUpdateResult
	(*PickUpPointDeleteRequest)(nil), // 9: pickuppoint.PickUpPointDeleteRequest
	(*PickUpPointDeleteResult)(nil),  // 10: pickuppoint.PickUpPointDeleteResult
}
var file_pickuppoint_proto_depIdxs = []int32{
	0,  // 0: pickuppoint.PickUpPointCreateRequest.point:type_name -> pickuppoint.PickUpPoint
	0,  // 1: pickuppoint.PickUpPointListResult.points:type_name -> pickuppoint.PickUpPoint
	0,  // 2: pickuppoint.PickUpPointGetResult.point:type_name -> pickuppoint.PickUpPoint
	0,  // 3: pickuppoint.PickUpPointUpdateRequest.point:type_name -> pickuppoint.PickUpPoint
	1,  // 4: pickuppoint.PickUpPointService.Create:input_type -> pickuppoint.PickUpPointCreateRequest
	3,  // 5: pickuppoint.PickUpPointService.List:input_type -> pickuppoint.PickUpPointListRequest
	5,  // 6: pickuppoint.PickUpPointService.Get:input_type -> pickuppoint.PickUpPointGetRequest
	7,  // 7: pickuppoint.PickUpPointService.Update:input_type -> pickuppoint.PickUpPointUpdateRequest
	9,  // 8: pickuppoint.PickUpPointService.Delete:input_type -> pickuppoint.PickUpPointDeleteRequest
	2,  // 9: pickuppoint.PickUpPointService.Create:output_type -> pickuppoint.PickUpPointCreateResult
	4,  // 10: pickuppoint.PickUpPointService.List:output_type -> pickuppoint.PickUpPointListResult
	6,  // 11: pickuppoint.PickUpPointService.Get:output_type -> pickuppoint.PickUpPointGetResult
	8,  // 12: pickuppoint.PickUpPointService.Update:output_type -> pickuppoint.PickUpPointUpdateResult
	10, // 13: pickuppoint.PickUpPointService.Delete:output_type -> pickuppoint.PickUpPointDeleteResult
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pickuppoint_proto_init() }
func file_pickuppoint_proto_init() {
	if File_pickuppoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pickuppoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointCreateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointListResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointGetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointUpdateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pickuppoint_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickUpPointDeleteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pickuppoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pickuppoint_proto_goTypes,
		DependencyIndexes: file_pickuppoint_proto_depIdxs,
		MessageInfos:      file_pickuppoint_proto_msgTypes,
	}.Build()
	File_pickuppoint_proto = out.File
	file_pickuppoint_proto_rawDesc = nil
	file_pickuppoint_proto_goTypes = nil
	file_pickuppoint_proto_depIdxs = nil
}
