// Code generated by MockGen. DO NOT EDIT.
// Source: ./pickuppoint.go
//
// Generated by this command:
//
//	mockgen -source=./pickuppoint.go -destination=../mocks/pickuppoint.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	core "homework/internal/app/core"
	pickuppoint "homework/internal/app/pickuppoint"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPickUpPointCoreService is a mock of PickUpPointCoreService interface.
type MockPickUpPointCoreService struct {
	ctrl     *gomock.Controller
	recorder *MockPickUpPointCoreServiceMockRecorder
}

// MockPickUpPointCoreServiceMockRecorder is the mock recorder for MockPickUpPointCoreService.
type MockPickUpPointCoreServiceMockRecorder struct {
	mock *MockPickUpPointCoreService
}

// NewMockPickUpPointCoreService creates a new mock instance.
func NewMockPickUpPointCoreService(ctrl *gomock.Controller) *MockPickUpPointCoreService {
	mock := &MockPickUpPointCoreService{ctrl: ctrl}
	mock.recorder = &MockPickUpPointCoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPickUpPointCoreService) EXPECT() *MockPickUpPointCoreServiceMockRecorder {
	return m.recorder
}

// CreatePoint mocks base method.
func (m *MockPickUpPointCoreService) CreatePoint(ctx context.Context, req core.CreatePointRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePoint", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePoint indicates an expected call of CreatePoint.
func (mr *MockPickUpPointCoreServiceMockRecorder) CreatePoint(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePoint", reflect.TypeOf((*MockPickUpPointCoreService)(nil).CreatePoint), ctx, req)
}

// DeletePoint mocks base method.
func (m *MockPickUpPointCoreService) DeletePoint(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePoint", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePoint indicates an expected call of DeletePoint.
func (mr *MockPickUpPointCoreServiceMockRecorder) DeletePoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePoint", reflect.TypeOf((*MockPickUpPointCoreService)(nil).DeletePoint), ctx, id)
}

// GetPoint mocks base method.
func (m *MockPickUpPointCoreService) GetPoint(ctx context.Context, id uint64) (pickuppoint.PickUpPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoint", ctx, id)
	ret0, _ := ret[0].(pickuppoint.PickUpPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoint indicates an expected call of GetPoint.
func (mr *MockPickUpPointCoreServiceMockRecorder) GetPoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoint", reflect.TypeOf((*MockPickUpPointCoreService)(nil).GetPoint), ctx, id)
}

// ListPoints mocks base method.
func (m *MockPickUpPointCoreService) ListPoints(ctx context.Context) ([]pickuppoint.PickUpPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPoints", ctx)
	ret0, _ := ret[0].([]pickuppoint.PickUpPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPoints indicates an expected call of ListPoints.
func (mr *MockPickUpPointCoreServiceMockRecorder) ListPoints(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPoints", reflect.TypeOf((*MockPickUpPointCoreService)(nil).ListPoints), ctx)
}

// UpdatePoint mocks base method.
func (m *MockPickUpPointCoreService) UpdatePoint(ctx context.Context, req core.UpdatePointRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePoint", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePoint indicates an expected call of UpdatePoint.
func (mr *MockPickUpPointCoreServiceMockRecorder) UpdatePoint(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePoint", reflect.TypeOf((*MockPickUpPointCoreService)(nil).UpdatePoint), ctx, req)
}

// MockPickUpPointService is a mock of PickUpPointService interface.
type MockPickUpPointService struct {
	ctrl     *gomock.Controller
	recorder *MockPickUpPointServiceMockRecorder
}

// MockPickUpPointServiceMockRecorder is the mock recorder for MockPickUpPointService.
type MockPickUpPointServiceMockRecorder struct {
	mock *MockPickUpPointService
}

// NewMockPickUpPointService creates a new mock instance.
func NewMockPickUpPointService(ctrl *gomock.Controller) *MockPickUpPointService {
	mock := &MockPickUpPointService{ctrl: ctrl}
	mock.recorder = &MockPickUpPointServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPickUpPointService) EXPECT() *MockPickUpPointServiceMockRecorder {
	return m.recorder
}

// CreatePoint mocks base method.
func (m *MockPickUpPointService) CreatePoint(ctx context.Context, point pickuppoint.PickUpPoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePoint", ctx, point)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePoint indicates an expected call of CreatePoint.
func (mr *MockPickUpPointServiceMockRecorder) CreatePoint(ctx, point any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePoint", reflect.TypeOf((*MockPickUpPointService)(nil).CreatePoint), ctx, point)
}

// DeletePoint mocks base method.
func (m *MockPickUpPointService) DeletePoint(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePoint", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePoint indicates an expected call of DeletePoint.
func (mr *MockPickUpPointServiceMockRecorder) DeletePoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePoint", reflect.TypeOf((*MockPickUpPointService)(nil).DeletePoint), ctx, id)
}

// GetPoint mocks base method.
func (m *MockPickUpPointService) GetPoint(ctx context.Context, id uint64) (pickuppoint.PickUpPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoint", ctx, id)
	ret0, _ := ret[0].(pickuppoint.PickUpPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoint indicates an expected call of GetPoint.
func (mr *MockPickUpPointServiceMockRecorder) GetPoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoint", reflect.TypeOf((*MockPickUpPointService)(nil).GetPoint), ctx, id)
}

// ListPoints mocks base method.
func (m *MockPickUpPointService) ListPoints(ctx context.Context) ([]pickuppoint.PickUpPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPoints", ctx)
	ret0, _ := ret[0].([]pickuppoint.PickUpPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPoints indicates an expected call of ListPoints.
func (mr *MockPickUpPointServiceMockRecorder) ListPoints(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPoints", reflect.TypeOf((*MockPickUpPointService)(nil).ListPoints), ctx)
}

// UpdatePoint mocks base method.
func (m *MockPickUpPointService) UpdatePoint(ctx context.Context, point pickuppoint.PickUpPoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePoint", ctx, point)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePoint indicates an expected call of UpdatePoint.
func (mr *MockPickUpPointServiceMockRecorder) UpdatePoint(ctx, point any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePoint", reflect.TypeOf((*MockPickUpPointService)(nil).UpdatePoint), ctx, point)
}
